// The schema browser: every document in schema/ rendered from the JSON-LD itself — modules, structs (fields with their
// bencode key, value type, BEP and description; derived values with their derivation), enumerations, rulesets with
// error codes. Nothing on this page is written by hand; add a document to MODULES and it appears.
const MODULES = ['bencode', 'metainfo', 'tracker', 'wire', 'webseed', 'webtorrent', 'nostr'];
const short = (id) => String(id).replace(/^bt:/, '');
const esc = (s) => String(s ?? '').replace(/[&<>]/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;' })[c]);
const typeOf = (f) => f.valueType === 'list' ? `list&lt;${String(f.itemType).startsWith('list:') ? `list&lt;${esc(String(f.itemType).slice(5))}&gt;` : f.itemType === 'struct' ? short(f.structType) : esc(f.itemType)}&gt;` : f.valueType === 'struct' ? short(f.structType) : esc(f.valueType);
const main = document.getElementById('classes'); main.innerHTML = '';
// the catalogue first: every node on one screen, from classes.json (generated with the pages, checked by the tests)
{ const cat = await (await fetch('classes.json')).json(); const sec = document.createElement('section'); sec.className = 'card'; sec.id = 'catalogue';
  const counts = cat.classes.reduce((a, c) => (a[c.type] = (a[c.type] ?? 0) + 1, a), {}); const withInst = cat.classes.filter((c) => c.instance).length;
  sec.innerHTML = `<h2>All classes</h2><div class="meta">${cat.classes.length} nodes · ${Object.entries(counts).map(([t, n]) => `${n} ${t}${n > 1 ? 's' : ''}`).join(', ')} · ${withInst} structs with a real captured instance · each name is its page, each page is its IRI · <a href="classes.json">classes.json</a></div>
    <table class="catalogue"><tr><th>node</th><th>kind</th><th>module</th><th>encoding</th><th>size</th><th>captured</th><th>what it is</th></tr>${cat.classes.map((c) => `<tr><td class="name"><a href="${esc(c.id)}">${esc(c.label)}</a></td><td class="type">${esc(c.type)}</td><td class="type"><a href="${esc(c.module)}" style="color:inherit">${esc(c.module)}</a></td><td class="type">${esc(c.encoding ?? '')}</td><td class="type">${c.wireSize ? c.wireSize + ' B' : c.fields ? c.fields + ' fields' : c.members ? c.members + ' members' : c.rules ? c.rules + ' rules' : ''}</td><td class="type">${c.instance ? (c.instance.bytes ? c.instance.bytes + ' bytes' : 'yes') : c.type === 'Struct' ? '<span style="color:var(--mut)">—</span>' : ''}</td><td class="desc" title="${esc(c.summary)}">${esc(c.summary.length > 96 ? c.summary.slice(0, 93).replace(/\s+\S*$/, '') + '…' : c.summary)}</td></tr>`).join('')}</table>`;
  main.appendChild(sec); }
document.getElementById('version').textContent = 'v' + (await (await fetch('package.json')).json()).version;
const wireRows = (fields) => fields.map((f) => `<tr><td class="name">${esc(f.label)}</td><td class="type">${f.wireType === 'struct' ? short(f.structType) : esc(f.wireType)}${f.repeat === 'toEnd' ? ' …to end' : ''}</td><td class="type">${f.constValue !== undefined ? '= ' + esc(f.constValue) : ''}</td><td class="desc">${esc(f.comment)}${f.enumType ? ` <span style="color:var(--mut)">(${esc(short(f.enumType))})</span>` : ''}</td></tr>`).join('');
const rows = (fields) => fields.map((f) => `<tr><td class="name">${esc(f.label)}</td><td class="type">${f.position !== undefined ? `[${esc(f.position)}]` : esc(f.key ?? '')}</td><td class="type">${typeOf(f)}${f.required ? '' : '?'}</td><td class="desc">${f.presentIf ? `<b style="color:var(--accent)">if ${esc(f.presentIf)}:</b> ` : ''}${esc(f.comment)}${f.bep ? ` <span style="color:var(--mut)">(BEP ${esc(f.bep)})</span>` : ''}</td></tr>`).join('');
const derivedRows = (d) => d.map((f) => `<tr><td class="name">${esc(f.label)}</td><td class="desc" colspan="3"><code>${esc(f.derivation)}</code>${f.comment ? `<br>${esc(f.comment)}` : ''}${f.bep ? ` <span style="color:var(--mut)">(BEP ${esc(f.bep)})</span>` : ''}</td></tr>`).join('');
for (const name of MODULES) {
  const doc = await (await fetch(`schema/${name}.jsonld`)).json(); const nodes = doc['@graph']; const mod = nodes.find((n) => n['@type'] === 'Module');
  const h = document.createElement('h2'); h.className = 'module'; h.innerHTML = `module: <a href="${esc(name)}" style="color:var(--accent)">${esc(name)}</a> · layer: ${esc(mod.layer)}${mod.bep ? ` · BEP ${esc([].concat(mod.bep).join(', '))}` : ''} · v${esc(mod.version)}`; main.appendChild(h);
  const intro = document.createElement('p'); intro.className = 'comment'; intro.style.color = 'var(--mut)'; intro.textContent = mod.comment; main.appendChild(intro);
  for (const node of nodes.filter((n) => n !== mod)) {
    const card = document.createElement('section'); card.className = 'card'; const type = node['@type'];
    const binary = String(node.encoding ?? '').endsWith('binary'), query = String(node.encoding ?? '').endsWith('urlquery') || String(node.encoding ?? '').endsWith('json');
    if (type === 'Struct') card.innerHTML = `<h2><a href="${esc(short(node['@id']))}">${esc(node.label)}</a></h2><div class="meta">struct · encoding ${esc(short(node.encoding))}${node.wireSize ? ` · <b>${esc(node.wireSize)} bytes</b> on the wire` : ''} · ${node.fields.length} fields${node.kind ? ` · <b>kind ${esc(node.kind)}</b>` : ''}${node.bep ? ` · BEP ${esc([].concat(node.bep).join(', '))}` : ''}</div><p class="comment">${esc(node.comment)}</p>
      ${binary ? `<table><tr><th>field</th><th>wire type</th><th>constant</th><th>description</th></tr>${wireRows(node.fields)}</table>` : `<table><tr><th>field</th><th>${String(node.encoding ?? '').endsWith('nostrTag') ? 'tag' : String(node.encoding ?? '').endsWith('json') ? 'JSON key' : query ? 'query key' : 'bencode key'}</th><th>type</th><th>description</th></tr>${rows(node.fields)}</table>`}
      ${node.derived ? `<div class="derived-label">derived (computed, never stored)</div><table><tr><th>value</th><th colspan="3">derivation</th></tr>${derivedRows(node.derived)}</table>` : ''}`;
    else if (type === 'Enumeration') card.innerHTML = `<h2><a href="${esc(short(node['@id']))}">${esc(node.label)}</a></h2><div class="meta">enumeration · ${node.members.length} members</div><p class="comment">${esc(node.comment)}</p>
      <table><tr>${node.members[0].code !== undefined ? '<th>code</th>' : ''}<th>member</th><th>description</th></tr>${node.members.map((m) => `<tr>${m.code !== undefined ? `<td class="type">${esc(m.code)}</td>` : ''}<td class="name">${esc(m.label)}</td><td class="desc">${esc(m.comment)}</td></tr>`).join('')}</table>`;
    else if (type === 'Encoding') card.innerHTML = `<h2><a href="${esc(short(node['@id']))}">${esc(node.label)}</a></h2><div class="meta">encoding</div><p class="comment">${esc(node.comment)}</p>`;
    else if (type === 'RuleSet') card.innerHTML = `<h2><a href="${esc(short(node['@id']))}">${esc(node.label)}</a></h2><div class="meta">ruleset · scope: <b>${esc(node.scope)}</b> · ${node.rules.length} rules · each with the error code the codec reports</div><p class="comment">${esc(node.comment)}</p>
      <table><tr><th>#</th><th>rule</th><th>error code</th><th>check</th></tr>${node.rules.map((r, i) => `<tr><td class="name">${i + 1}</td><td class="desc">${esc(r.label)}</td><td class="type">${esc(r.errorCode)}</td><td class="desc"><code>${esc(r.check)}</code></td></tr>`).join('')}</table>`;
    else card.innerHTML = `<h2>${esc(node.label)}</h2><div class="meta">${esc(short(type))}</div><p class="comment">${esc(node.comment)}</p>`;
    main.appendChild(card);
  }
}
